name: Django Application

on: [pull_request]

jobs:
  build:
    env:
      DEBUG: False
      DATABASE_URL: sqlite:///db.sqlite3
      SECRET_KEY: VeryRandomString

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
